SET SEARCH_PATH = "nutrifoods";

INSERT INTO ingredient (name, is_animal, food_group)

VALUES ('Sal', false, 23),
       ('Pimienta negra', false, 23),
       ('Aceite de oliva', false, 21),
       ('Cebolla', false, 7),
       ('Ajo', false, 7),
       ('Huevo', true, 14),
       ('Tomate', false, 4),
       ('Mantequilla', false, 18),
       ('Limón', false, 7),
       ('Zanahoria', false, 4),
       ('Cilantro', false, 3),
       ('Aceite', false, 21),
       ('Sal de mar', false, 23),
       ('Mayonesa', true, 24),
       ('Palta', false, 7),
       ('Albahaca', false, 3),
       ('Perejil', false, 3),
       ('Comino', false, 23),
       ('Pimiento rojo', false, 4),
       ('Crema', true, 13),
       ('Puré de papas', true, 6),
       ('Jugo de limón', false, 2),
       ('Orégano', false, 23),
       ('Queso parmesano', true, 20),
       ('Lechuga', false, 3),
       ('Queso crema', true, 20),
       ('Pimienta blanca', false, 23),
       ('Leche semidescremada', true, 18),
       ('Zapallo italiano', false, 3),
       ('Espinaca', false, 3),
       ('Champiñón', false, 7),
       ('Azúcar', false, 22),
       ('Mostaza', false, 23),
       ('Ají color', false, 23),
       ('Queso', true, 20),
       ('Berenjena', false, 1),
       ('Cebollín', false, 7),
       ('Ajo en polvo', false, 23),
       ('Tomate cherry', false, 1),
       ('Almendras', false, 15),
       ('Harina', false, 9),
       ('Tomillo', false, 23),
       ('Brócoli', false, 3),
       ('Choclo', false, 8),
       ('Espárrago', false, 3),
       ('Vinagre de manzana', false, 24),
       ('Jengibre', false, 7),
       ('Apio', false, 3),
       ('Leche evaporada', true, 18),
       ('Papa', false, 6),
       ('Merkén', false, 23),
       ('Manzana', false, 1),
       ('Pechuga de pollo', true, 13),
       ('Vinagre', false, 24),
       ('Garbanzos', false, 5),
       ('Atún', true, 10),
       ('Vainilla', false, 17),
       ('Aceite de coco', false, 21),
       ('Leche', true, 18),
       ('Queso mozzarella', true, 20),
       ('Salmón', true, 10),
       ('Aceite de palta', false, 21),
       ('Repollo', false, 3),
       ('Aceituna', false, 7),
       ('Arvejas', false, 5),
       ('Pepino', false, 3),
       ('Porotos verdes', false, 3),
       ('Aceituna negra', false, 7),
       ('Sésamo', false, 16),
       ('Linaza', false, 16),
       ('Polvo de hornear', false, 24),
       ('Canela', false, 23),
       ('Zapallo', false, 3),
       ('Curry', false, 23),
       ('Nuez moscada', false, 23),
       ('Queso cheddar', true, 20),
       ('Salsa de tomate', false, 24),
       ('Harina de almendra', false, 24),
       ('Pimiento verde', false, 3),
       ('Ciboulette', false, 7),
       ('Queso cabra', true, 20),
       ('Vinagre balsámico', false, 24),
       ('Laurel', false, 23),
       ('Cebolla morada', false, 7),
       ('Tahini', false, 16),
       ('Bicarbonato', false, 24),
       ('Vino blanco', false, 25),
       ('Cebolla en polvo', false, 23),
       ('Camarón', true, 11),
       ('Tocino', true, 12),
       ('Carne molida', true, 12),
       ('Betarraga', false, 7),
       ('Carne', true, 12),
       ('Nueces', false, 15),
       ('Alcaparra', false, 24),
       ('Alcachofa', false, 7),
       ('Lentejas', false, 5),
       ('Miel', false, 22),
       ('Menta', false, 23),
       ('Eneldo', false, 23),
       ('Salsa inglesa', false, 23),
       ('Naranja', false, 1),
       ('Sal rosada', false, 23),
       ('Arroz', false, 9),
       ('Vinagre blanco', false, 24),
       ('Levadura', false, 24),
       ('Pimiento amarillo', false, 7),
       ('Muslo de pollo', true, 13),
       ('Vinagre de vino blanco', false, 24),
       ('Cerdo', true, 12),
       ('Eritritol', false, 22),
       ('Harina de garbanzos', false, 24),
       ('Cuscús', false, 9),
       ('Ají', false, 7),
       ('Palmito', false, 7),
       ('Pan', false, 9),
       ('Anchoa', true, 10),
       ('Chalota', false, 7),
       ('Frutilla', false, 1),
       ('Porotos', false, 5),
       ('Mote', false, 9),
       ('Pasas', false, 1),
       ('Ají verde', false, 7),
       ('Miel de maple', false, 11),
       ('Maicena', false, 9),
       ('Jugo de naranja', false, 2),
       ('Cacao en polvo', false, 24),
       ('Granada', false, 1),
       ('Tomate en tarro', false, 4),
       ('Estragón', false, 23),
       ('Porotos granados', false, 5),
       ('Ají en polvo', false, 23),
       ('Vino tinto', false, 25),
       ('Ají rojo', false, 7),
       ('Jalapeño', false, 7),
       ('Leche de coco', false, 18),
       ('Piñón', false, 15),
       ('Coliflor', false, 7),
       ('Jamón', true, 12),
       ('Pepinillo', false, 7),
       ('Amapola', false, 16),
       ('Crema de coco', false, 24),
       ('Harina de maíz', false, 9),
       ('Ulte', false, 26),
       ('Rúcula', false, 7),
       ('Paprika', false, 23),
       ('Maracuyá', false, 1),
       ('Escalopa de carne', true, 12),
       ('Papas fritas', false, 24),
       ('Ketchup', false, 23),
       ('Piña', false, 1),
       ('Plátano', false, 1),
       ('Arándano', false, 1),
       ('Yogurt', false, 19),
       ('Cochayuyo', false, 26),
       ('Acelga', false, 3),
       ('Quinoa', false, 8),
       ('Maíz', false, 6),
       ('Salsa de ají', false, 23),
       ('Salsa de soya', false, 23),
       ('Caldo de verduras', false, 23),
       ('Zapallo spaghetti', false, 7),
       ('Leche de almendra', false, 18),
       ('Cúrcuma', false, 23),
       ('Azúcar rubia', false, 22),
       ('Castañas', false, 15),
       ('Dátiles', false, 15),
       ('Tomate pera', false, 4),
       ('Cebolla chalota', false, 7),
       ('Papa camote', false, 6),
       ('Ciruela', false, 1),
       ('Damasco turco', false, 1),
       ('Higo', false, 1),
       ('Zapallo camote', false, 7),
       ('Zapallo butternut', false, 7),
       ('Cardamomo', false, 23),
       ('Avena', false, 9),
       ('Mermelada de frambuesa', false, 24),
       ('Azafrán', false, 23),
       ('Lechuga escarola', false, 3),
       ('Tortilla', false, 9),
       ('Caldo de ave', true, 13),
       ('Habas', false, 5),
       ('Granos de choclo', false, 6),
       ('Tapas de empanadas', true, 24),
       ('Pesto', false, 23),
       ('Carne vegetal', false, 24),
       ('Tortilla de maíz', false, 9),
       ('Concentrado de tomate', false, 23),
       ('Crema ácida', true, 18),
       ('Pan rallado', false, 9),
       ('Puré de zapallo', false, 24),
       ('Salvia deshidratada', false, 23),
       ('Clara de huevo', true, 14),
       ('Pasta de ají', false, 23),
       ('Salsa de tabasco', false, 23),
       ('Lomo de ternera', true, 12),
       ('Queso azul', true, 20),
       ('Yogurt griego', true, 19),
       ('Anato', false, 23),
       ('Pescado blanco', true, 10),
       ('Fiambre de pollo', true, 13),
       ('Especias italianas', false, 23),
       ('Queso provoleta', true, 20),
       ('Chorizo', true, 12),
       ('Pasta de chipotle', false, 23),
       ('Romero', false, 23),
       ('Harina de coco', false, 24),
       ('Bistec', true, 12),
       ('Caldo de carne', true, 23),
       ('Aceituna verde', false, 7),
       ('Jugo de almeja', true, 11),
       ('Pasta de curry', false, 23),
       ('Chocolate', true, 24),
       ('Semillas de zapallo', false, 16),
       ('Yema de huevo', true, 14),
       ('Mandarina', false, 1),
       ('Bacalao', true, 10),
       ('Rábano', false, 7),
       ('Chuleta de cerdo', true, 12),
       ('Uvas', false, 1),
       ('Pasta sin gluten', false, 9),
       ('Carne de cordero', true, 12),
       ('Rabo de ternera', true, 12),
       ('Cebolla perla', false, 7),
       ('Mostaza en grano', false, 23),
       ('Masa para pizza sin gluten', false, 9),
       ('Huevo de codorniz', true, 14),
       ('Cola de langostino', true, 11),
       ('Calamar', true, 11),
       ('Solomillo de cerdo', true, 12),
       ('Whisky', false, 25),
       ('Kanikama', true, 11),
       ('Leche condensada', true, 22),
       ('Manjar', true, 22),
       ('Cobertura de chocolate semi-amargo', true, 23),
       ('Filete', true, 12),
       ('Salsa de caramelo', false, 22),
       ('Galletas', true, 9),
       ('Ostiones', true, 11),
       ('Berries', false, 1),
       ('Ralladura de limón', false, 7),
       ('Marraqueta', false, 9),
       ('Clavo de olor', false, 23),
       ('Machas', true, 11),
       ('Plateada', true, 10),
       ('Jerez', false, 25),
       ('Salsa blanca', true, 18),
       ('Crispy', false, 23),
       ('Brandy', false, 25),
       ('Panqueque', false, 9),
       ('Ralladura de naranja', false, 23),
       ('Fondant', false, 22),
       ('Chancaca', false, 22),
       ('Durazno', false, 1),
       ('Pera', false, 1),
       ('Moras', false, 1),
       ('Galletas de champaña', false, 9),
       ('Pulpo', true, 11),
       ('Lomo liso', true, 12),
       ('Posta', true, 12),
       ('Manteca', true, 18),
       ('Pollo ganso', true, 12),
       ('Jaiba', true, 11),
       ('Pan integral', false, 9),
       ('Lomo vetado', true, 12),
       ('Trutros cortos', true, 12),
       ('Cerveza', false, 25),
       ('Congrio', true, 10),
       ('Champiñones ostra', false, 7),
       ('Coñac', false, 25),
       ('Pisco', false, 25),
       ('Café', false, 24),
       ('Esencia de ron', false, 25),
       ('Crema pastelera', true, 18),
       ('Manteca vegetal', false, 21),
       ('Pan de hamburguesa', true, 9),
       ('Oporto', false, 25),
       ('Almejas', true, 11),
       ('Cobertura de chocolate blanco', true, 24),
       ('Bizcocho', true, 9),
       ('Anís estrella', false, 23),
       ('Ajo granulado', false, 23),
       ('Anís', false, 23),
       ('Salsa barbecue', false, 23),
       ('Asiento', true, 12),
       ('Dientes de dragón', false, 7),
       ('Champiñones de París', false, 7),
       ('Ron', false, 25),
       ('Nutella', false, 24),
       ('Huesillo', false, 1),
       ('Cerezas', false, 1),
       ('Coco', false, 1),
       ('Pistachos', false, 15),
       ('Brownies', true, 9),
       ('Helado', true, 18),
       ('Endulzante', false, 22),
       ('Sucralosa', false, 22),
       ('Semillas de anís', false, 23),
       ('Café granulado', false, 24),
       ('Amaretto', false, 25),
       ('Licor', false, 25),
       ('Esencia de cola de mono', false, 25),
       ('Salsa de frambuesa', false, 24),
       ('Compota de manzana', false, 24),
       ('Cacao amargo', false, 24),
       ('Higo deshidratado', false, 15),
       ('Berro', false, 5),
       ('Colapez', true, 23),
       ('Mariscos surtidos', true, 11),
       ('Masa filo', true, 9),
       ('Merluza austral', true, 10),
       ('Salsa teriyaki', false, 23),
       ('Polenta', false, 9),
       ('Punta de ganso', true, 12),
       ('Pollo entero', true, 12),
       ('Sémola', false, 9),
       ('Mariscos', true, 11),
       ('Choros', true, 11),
       ('Salsa de pescado', true, 10),
       ('Maní', false, 5),
       ('Trutro de pollo', true, 12),
       ('Cranberries', false, 1),
       ('Pasta espiral', false, 9),
       ('Pan de molde blanco', false, 9),
       ('Ají Rocoto', false, 4),
       ('Trigo', false, 8),
       ('Hojas de parra', false, 7),
       ('Baguette', false, 9),
       ('Salsa horseradish', false, 23),
       ('Achiote', false, 23),
       ('Jugo de piña', false, 2),
       ('Fideos de ramen', false, 9),
       ('Mango', false, 1),
       ('Crutones', false, 9),
       ('Churrasco', true, 12),
       ('Prieta', true, 12),
       ('Merluza', true, 10),
       ('Trigo burgol', false, 8),
       ('Palanca', true, 12),
       ('Ají cacho de cabra', false, 4),
       ('Pan amasado', false, 9),
       ('Pan ciabatta', false, 9),
       ('Asado de tira', true, 12),
       ('Cerveza oscura', false, 25),
       ('Tallarines', false, 9),
       ('Pimienta cayenna', false, 23),
       ('Malaya', true, 12),
       ('Pasta penne', false, 9),
       ('Osobuco', true, 12),
       ('Caldo de costilla', true, 12),
       ('Posta paleta', true, 12),
       ('Charqui', true, 12),
       ('Fideos cabello', false, 9),
       ('Tallarines de arroz', false, 9),
       ('Locos', true, 11),
       ('Láminas de lasaña', false, 9),
       ('Masa de hoja', false, 9),
       ('Callampas deshidratadas', false, 7),
       ('Salsa de ostras', true, 11),
       ('Cerveza negra', false, 25),
       ('Sobrecostilla', true, 12),
       ('Champiñones shiitake', false, 7),
       ('Filete de corvina', true, 10),
       ('Arroz silvestre', false, 8),
       ('Champiñones portobello', false, 7),
       ('Congrio colorado', true, 10),
       ('Cabeza de congrio', true, 10),
       ('Cabeza de pescado', true, 10),
       ('Pierna de cordero', true, 12),
       ('Lemon grass', false, 23),
       ('Tagliatelle', false, 9),
       ('Tomate deshidratado', false, 4),
       ('Tilapia', true, 10),
       ('Merlot', false, 25),
       ('Pavo', true, 12),
       ('Reineta', true, 10),
       ('Brotes de arveja', false, 7),
       ('Salsa de champiñón', false, 23),
       ('Choros zapato', true, 11),
       ('Fettuccine', false, 9),
       ('Jibia', true, 11),
       ('Sierra', true, 10),
       ('Abastero', true, 12),
       ('Vienesa', true, 12),
       ('Tapapecho', true, 12),
       ('Marshmallows', true, 22),
       -- nuevos ingredientes--
       ('Salmón Ahumado', true, 10),
       ('Lechuga costina', false, 3),
       ('Queso ricotta', true, 20),
       ('Porotos negros', false, 5),
       ('Salsa de ajo', false, 24),
       ('Queso feta', true, 20),
       ('Puerro', false, 3),
       ('Jugo de tomate', false, 4),
       ('Caldo de pescado', true, 10),
       ('Pechuga de pavo', true, 13),
       ('Centolla', true, 11),
       ('Salsa de queso', true, 20),
       ('Queso gruyere', true, 20),
       ('Pulpa de cerdo', true, 12),
       ('Aceite de sésamo', false, 21),
       ('Arroz basmati', false, 9),
       ('Salsa de carne', true, 12),
       ('Coco rallado', false, 24),
       ('Queso roquefort', true, 20),
       ('Canelón', true, 9),
       ('Jamón serrano', true, 12),
       ('Humo líquido', false, 24),
       ('Alga nori', false, 26),
       ('Harina integral', false, 8),
       ('Azúcar flor', false, 22),
       ('Pechuga de pato', true, 12),
       ('Mantequilla de maní', false, 24),
       ('Chocolate amargo', false, 24),
       ('Ciruela deshidratada', false, 15),
       ('Vinagre de arroz', false, 24),
       ('Arroz arbóreo', false, 9),
       ('Salsa de pimienta', false, 24),
       ('Pure de tomate', false, 4),
       ('Pan pita', false, 9),
       ('Arroz integral', false, 8),
       ('Pulpa de lúcuma', false, 24),
       ('Salsa de chocolate', false, 24),
       ('Jalea de frambuesa', false, 24),
       ('Chocolate amargo en polvo', false, 24),
       ('Chips de chocolate', false, 24),
       ('Chocolate blanco', true, 24),
       ('Frambuesa', false, 1),
       ('Puré de lúcuma', false, 24),
       ('Esencia de naranja', false, 24),
       ('Esencia de limón', false, 24),
       ('Merengue', true, 14),
       ('Flan de vainilla', true, 24),
       ('Salsa de frutilla', true, 24),
       ('Cereal de arroz', false, 9),
       ('Papaya', false, 1),
       ('Licor de naranja', false, 24),
       ('Jarabe de maíz', false, 22),
       ('Damasco', false, 1),
       ('Manzana deshidratada', false, 15),
       ('Glaseado de vainilla', false, 24),
       ('Colorante rojo', true, 24),
       ('Mayonesa vegana', false, 24),
       ('Costillar de cerdo', true, 12),
       ('Soda', false, 24),
       ('Galletas de soda', false, 9),
       ('Endivia', false, 3),
       ('Alfalfa', false, 3),
       ('Gelatina', true, 24),
       ('Hígado', true, 12),
       ('Queso camembert', true, 20),
       ('Agua mineral', false, 24),
       ('Tequila', false, 25),
       ('Granadina', false, 24),
       ('Tofu', false, 5),
       ('Tortellini', false, 9),
       ('Trucha', true, 10),
       ('Cereal', false, 8),
       ('Kiwi', false, 1),
       ('Margarina', false, 21),
       ('Membrillo', false, 1),
       ('Aceite de canola', false, 21),
       ('Harina de arroz', false, 9),
       ('Nesquik', true, 24),
       ('Kale', false, 3),
       ('Jugo de coco', false, 2),
       ('Jugo de maracuyá', false, 2),
       ('Semillas de chía', false, 8),
       ('Semillas de girasol', false, 8),
       ('Té', false, 24),
       ('Anacardos', false, 15),
       ('Salami', true, 12)
;